---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: Create Backend Directory
    become: yes
    file:
      path: /home/ubuntu/backend
      state: directory

  - name: "Copy and Extract Backend"
    become: yes
    unarchive:
      src: backend-artifact.tar.gz
      dest: /home/ubuntu/backend

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    args:
      chdir: /home/ubuntu/backend
    command: pm2 start npm -- start
