---
  - name: "Create Backend Directory"
    become: yes
    file:
      path: /home/ubuntu/backend
      state: directory

  - name: "Copy and Extract Backend"
    become: yes
    unarchive:
      src: backend-artifact.tar.gz
      dest: /home/ubuntu/backend

  - name: "Start Server"
    become: true
    args:
      chdir: /home/ubuntu/backend
    command: pm2 start npm -- start
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "src/migrations"
      TYPEORM_MIGRATIONS: "src/migrations/*.js"
      TYPEORM_ENTITIES: "src/modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"