---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: "copy backend"
    become: yes
    synchronize:
      src: ../../backend
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    args:
      chdir: /home/ubuntu/uda_app/backend
    command: pm2 start -f ./dist/main.js
    environment:
      # - ENVIRONMENT: "{{ lookup('env', 'ENVIRONMENT') }}"
#      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
#      - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
#      - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
#      - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
#      - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
#      - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
#      - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
#      - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
#      - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"