---
  - name: "Copy and Extract Backend"
    become: yes
    unarchive:
      src: backend-artifact.tar.gz
      dest: /home/ubuntu/backend

  - name: "Start Server"
    become: true
    args:
      chdir: /home/ubuntu/backend
    command: pm2 start npm -- start
